[package]
name = "example01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum_dispatch = "0.3.8"
anyhow = "1.0"
bytes = "1"
moka = { version = "0.9", features = ["future"] }
dyn-clone = "1.0.14"